const Chair = {
  massiv: [
    {
    id: 01 ,
    picture:"/public/img/chair/solo-ru.jpg",
    name: "Соло Ру" ,
    type: "Стулья" ,
    size: "",
    description:" с ортопедическим основанием" ,
    prise:"2 100 ₽",
  },
  {
    id: 02 ,
    picture:"/public/img/chair/sonata-t.jpg",
    name: "Соната Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 150 ₽",
  },
  {
    id: 03 ,
    picture:"/public/img/chair/trilogiya-ru.jpg",
    name: "Трилогия Ру" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 250 ₽",
  },
  {
    id: 04 ,
    picture:"/public/img/chair/unison.jpg",
    name: "Унисон Ру" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 300 ₽",
  },
  {
    id: 05 ,
    picture:"/public/img/chair/fagot-mru.jpg",
    name: "Фагот МРу" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 750 ₽", 
  },
  {
    id: 06,
    picture:"/public/img/chair/fagot-mt.jpg",
    name: "Фагот МТ",
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 600 ₽", 
  },
  {
    id: 07 ,
    picture:"/public/img/chair/furiant-ru.jpg",
    name: "Фуриант Ру" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:" 2 500 ₽", 
  },
  {
    id: 08 ,
    picture:"/public/img/chair/centurion-mru.jpg",
    name: "Центурион МРУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:" 3 000 ₽", 
  },
  {
    id: 09 ,
    picture:"/public/img/chair/alfa-mru.jpg",
    name: "Альфа МРУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:" 2 600 ₽", 
  },
  {
    id: 10 ,
    picture:"/public/img/chair/arietta-ru.jpg",
    name: "Ариетта РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:" 2 700 ₽", 
  },
  {
    id: 011 ,
    picture:"/public/img/chair/arfa-ru.jpg",
    name: "Арфа Ру" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:" 2 900 ₽", 
  },
  {
    id: 12 ,
    picture:"/public/img/chair/bar-vr.jpg",
    name: "Барный врощающийся стул" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"4 000 ₽", 
  },
  {
    id: 13 ,
    picture:"/public/img/chair/volna.jpg",
    name: "Волна " ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"4 200 ₽", 
  },
  {
    id: 14 ,
    picture:"/public/img/chair/volna2.jpg",
    name: "Волна 2" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"4 400 ₽", 
  },
  {
    id: 15 ,
    picture:"/public/img/chair/volna4.jpg",
    name: "Волна 4" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:" 5 000 ₽", 
  },
  {
    id: 16 ,
    picture:"/public/img/chair/gamma-ru.jpg",
    name: "Гамма Ру" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 250 ₽", 
  },
  {
    id: 17 ,
    picture:"/public/img/chair/gamma-t.jpg",
    name: "Гамма Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 200 ₽", 
  },
  {
    id: 18 ,
    picture:"/public/img/chair/grazia-2t.jpg",
    name: "Грация 2Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 400 ₽", 
  },
  {
    id: 19 ,
    picture:"/public/img/chair/gracia-ru.jpg",
    name: "Грация Ру " ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 250 ₽", 
  },
  {
    id: 20 ,
    picture:"/public/img/chair/gracia-t.jpg",
    name: "Грация Т " ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 150 ₽", 
  },
  {
    id: 21 ,
    picture:"/public/img/chair/damask.jpg",
    name: "Дамаск " ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"7 000 ₽", 
  },
  {
    id: 22 ,
    picture:"/public/img/chair/jacozo-mt.jpg",
    name: "Джакозо МТ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 700 ₽", 
  },
  {
    id: 23 ,
    picture:"/public/img/chair/diva-mt.jpg",
    name: "Дива МТ " ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 700 ₽", 
  },
  {
    id: 24 ,
    picture:"/public/img/chair/diez-ru.jpg",
    name: "Диез РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 200 ₽", 
  },
  {
    id: 25 ,
    picture:"/public/img/chair/diez-t.jpg",
    name: "Диез Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 200 ₽", 
  },
  {
    id: 26 ,
    picture:"/public/img/chair/dolche-mru.jpg",
    name: "Дольче МРУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 800 ₽", 
  }, 
  {
    id: 27 ,
    picture:"/public/img/chair/kvartet-mt.jpg",
    name: "Квартет МТ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 700 ₽", 
  }, 
  {
    id: 28 ,
    picture:"/public/img/chair/kvartet-ru.jpg",
    name: "Квартет РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 150 ₽", 
  }, 
  {
    id: 29 ,
    picture:"/public/img/chair/kvintet-2t.jpg",
    name: "Квинтет 2Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 700 ₽", 
  }, 
  {
    id: 30 ,
    picture:"/public/img/chair/kvintet-t.jpg",
    name: "Квинтет Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 150 ₽", 
  }, 
  {
    id: 31 ,
    picture:"/public/img/chair/libretto-ru.jpg",
    name: "Либретто РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 800 ₽", 
  }, 
  {
    id: 32 ,
    picture:"/public/img/chair/lotos-t.jpg",
    name: "Лотос Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 300 ₽", 
  }, 
  {
    id: 33 ,
    picture:"/public/img/chair/luch-t.jpg",
    name: "Луч Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 200 ₽", 
  },
  {
    id: 34 ,
    picture:"/public/img/chair/mayamy.jpg",
    name: "Маями" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"5 800 ₽", 
  },
  {
    id: 35 ,
    picture:"/public/img/chair/marsel.jpg",
    name: "Марсель" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"6 800 ₽", 
  },
  {
    id: 36 ,
    picture:"/public/img/chair/octava-t.jpg",
    name: "Октава Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 500 ₽", 
  },
  {
    id: 37,
    picture:"/public/img/chair/onda-ru.jpg",
    name: "Онда РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 250 ₽", 
  },
  {
    id: 38,
    picture:"/public/img/chair/pavlin-t.jpg",
    name: "Павлин Т" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 250 ₽", 
  },
  {
    id: 39 ,
    picture:"/public/img/chair/silver1.jpg",
    name: "Сильвер 1" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"5 650 ₽", 
  },
  {
    id: 40 ,
    picture:"/public/img/chair/silver2.jpg",
    name: "Сильвер 2" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"6 900 ₽", 
  },
  {
    id: 41 ,
    picture:"/public/img/chair/sclad-toburet.jpg",
    name: "Складной табурет" ,
    type: "Стулья" ,
    size: "",
    description:"может быть с квадратной сидушкой и с круглой сидушкой" ,
    prise:"1 950 ₽", 
  },
  {
    id: 42 ,
    picture:"/public/img/chair/soprano-ru.jpg",
    name: "Сопрано РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 450 ₽", 
  },
  {
    id: 43 ,
    picture:"/public/img/chair/tenor-ru.jpg",
    name: "Тенор РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 100 ₽", 
  },
  {
    id: 44 ,
    picture:"/public/img/chair/tetris.jpg",
    name: "Тетрис" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 750 ₽", 
  },
  {
    id: 45 ,
    picture:"/public/img/chair/triol-k.jpg",
    name: "Триоль К" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 400 ₽", 
  },
  {
    id: 46 ,
    picture:"/public/img/chair/falcet-k.jpg",
    name: "Фальцет К" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 550 ₽", 
  },
  {
    id: 47 ,
    picture:"/public/img/chair/fuga-k.jpg",
    name: "Фуга К" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 300 ₽", 
  },
  {
    id: 48 ,
    picture:"/public/img/chair/canon-ru.jpg",
    name: "Канон РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 950 ₽", 
  },
  {
    id: 49 ,
    picture:"/public/img/chair/kvatrol.jpg",
    name: "Кватроль" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 200 ₽", 
  },
  {
    id: 50 ,
    picture:"/public/img/chair/cobra-ru.jpg",
    name: "Кобра РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 900 ₽", 
  },
  {
    id: 51 ,
    picture:"/public/img/chair/krest-k.jpg",
    name: "Крест К" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 250 ₽", 
  },
  {
    id: 52 ,
    picture:"/public/img/chair/Lira-n-ru.jpg",
    name: "Лира Н РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 450 ₽", 
  },
  {
    id: 53 ,
    picture:"/public/img/chair/lira-ru.jpg",
    name: "Лира РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 450 ₽", 
  },
  {
    id: 54 ,
    picture:"/public/img/chair/pauk-ru.jpg",
    name: "Паук Ру" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"2 150 ₽", 
  },
  {
    id: 55 ,
    picture:"/public/img/chair/rondo-ru.jpg",
    name: "Рондо РУ" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"1 500 ₽", 
  },
  {
    id: 56 ,
    picture:"/public/img/chair/boston.jpg",
    name: "Бостон" ,
    type: "Стулья" ,
    size: "",
    description:"" ,
    prise:"6 900 ₽", 
  },
]
}